import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/footer";
import { TanStackProvider } from "@/Providers/TanStackProvider";

import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <TanStackProvider>
          <Navbar />
          {children}
          <Footer />
        </TanStackProvider>
      </body>
    </html>
  );
}
